import type { CatalogueProduct } from "./types";

/**
 * ARP's live catalogue, transcribed from the client stock lists dated 02 July 2026:
 * COSCO PRODUCTS, STIGA TT BAT, STIGA TT BALLS and STIGA TT TABLE & NET.
 * Names, SKUs (EAN barcodes) and AED retail prices are kept verbatim from those sheets.
 */
export const catalogueProducts: CatalogueProduct[] = [
  {
    slug: "cosco-agility-ladder-active",
    name: "COSCO AGILITY LADDER ACTIVE",
    sku: "8901793280438",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 95,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-ankle-weight-1-kg",
    name: "COSCO ANKLE WEIGHT 1 KG",
    sku: "8901793280582",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Fitness",
    priceAed: 70,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-ankle-weight-2-kg",
    name: "COSCO ANKLE WEIGHT 2 KG",
    sku: "8901793280865",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Fitness",
    priceAed: 130,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-ball-stand-display",
    name: "COSCO BALL STAND DISPLAY",
    sku: "8901793280483",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 4,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-basketball-inova-7",
    name: "COSCO BASKETBALL INOVA-7",
    sku: "8901793130467",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 103,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-premier-size-7",
    name: "COSCO BASKETBALL PREMIER SIZE-7",
    sku: "8901793130337",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 40,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-pulse-7",
    name: "COSCO BASKETBALL PULSE-7",
    sku: "8901793130290",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 80,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-super-6",
    name: "COSCO BASKETBALL SUPER-6",
    sku: "8901793130160",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 53,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-basketball-super-7",
    name: "COSCO BASKETBALL SUPER-7",
    sku: "8901793130047",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 53,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-basketball-tournament-7",
    name: "COSCO BASKETBALL TOURNAMENT-7",
    sku: "8901793130030",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 70,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-challenge-7",
    name: "COSCO BASKETBALL CHALLENGE-7",
    sku: "8901793130043",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 155,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-premier-size-3",
    name: "COSCO BASKETBALL PREMIER SIZE-3",
    sku: "8901793130375",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 20,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-premier-size-5",
    name: "COSCO BASKETBALL PREMIER SIZE-5",
    sku: "8901793130351",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 40,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-basketball-premier-size-6",
    name: "COSCO BASKETBALL PREMIER SIZE-6",
    sku: "8901793130344",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Basketball",
    priceAed: 40,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-england-5",
    name: "COSCO FOOTBALL ENGLAND-5",
    sku: "8901793140589",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 45,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-mundial-5",
    name: "COSCO FOOTBALL MUNDIAL-5",
    sku: "8901793140138",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 37,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-munich-5",
    name: "COSCO FOOTBALL MUNICH -5",
    sku: "8901793140336",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 97,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-platina-fifa-quality-pro-5",
    name: "COSCO FOOTBALL PLATINA FIFA QUALITY PRO -5",
    sku: "8901793140237",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 170,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-portugal-5",
    name: "COSCO FOOTBALL PORTUGAL-5",
    sku: "8901793140596",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 38,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-rio-3",
    name: "COSCO FOOTBALL RIO-3",
    sku: "8901793140268",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 30,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-torino-4",
    name: "COSCO FOOTBALL TORINO-4",
    sku: "8901793140633",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 64,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-torino-5",
    name: "COSCO FOOTBALL TORINO-5",
    sku: "8901793140220",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 70,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-football-shoes-ultra",
    name: "COSCO FOOTBALL SHOES ULTRA",
    sku: "890179338007",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 60,
    unit: "Pair",
    inStock: true,
  },
  {
    slug: "cosco-handball-goal-mini",
    name: "COSCO HANDBALL GOAL-MINI",
    sku: "8901793160037",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 57,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-handball-goal-men",
    name: "COSCO HANDBALL GOAL-MEN",
    sku: "8901793160013",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 66,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-handball-goal-women",
    name: "COSCO HANDBALL GOAL-WOMEN",
    sku: "8901793160020",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 65,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-bat-grip-chevron-ringh",
    name: "COSCO BAT GRIP CHEVRON RINGH",
    sku: "8901793190331",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Fitness",
    priceAed: 5,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-bat-grip-octopus",
    name: "COSCO BAT GRIP OCTOPUS",
    sku: "8901793190355",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Fitness",
    priceAed: 7,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-batting-gloves-county",
    name: "COSCO BATTING GLOVES COUNTY",
    sku: "8901793190072",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 58,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-batting-gloves-predator",
    name: "COSCO BATTING GLOVES PREDATOR",
    sku: "8901793190317",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 140,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-batting-gloves-test",
    name: "COSCO BATTING GLOVES TEST",
    sku: "8901793190065",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 93,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-bibs-play-flouro-green-junior",
    name: "COSCO BIBS PLAY FLOURO GREEN JUNIOR",
    sku: "8901793289578",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-bibs-play-flouro-green-senior",
    name: "COSCO BIBS PLAY FLOURO GREEN SENIOR",
    sku: "8901793289561",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-bibs-play-flouro-red-junior",
    name: "COSCO BIBS PLAY FLOURO RED JUNIOR",
    sku: "8901793289554",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-bibs-play-flouro-red-senior",
    name: "COSCO BIBS PLAY FLOURO RED SENIOR",
    sku: "8901793289547",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cone-15",
    name: "COSCO CONE 15\"",
    sku: "8901793280476",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cone-6",
    name: "COSCO CONE 6\"",
    sku: "8901793280445",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 5,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cone-9",
    name: "COSCO CONE 9\"",
    sku: "8901793280452",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 7,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-linesman-flags-red-green-pass",
    name: "COSCO LINESMAN FLAGS RED & GREEN PASS",
    sku: "8901793289524",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 30,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-corner-flags-with-springs-game",
    name: "COSCO CORNER FLAGS WITH SPRINGS GAME",
    sku: "8901793289516",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 100,
    unit: "Set",
    inStock: false,
  },
  {
    slug: "cosco-cricket-bat-blaster-full",
    name: "COSCO CRICKET BAT BLASTER FULL",
    sku: "8901793180196",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 80,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-bat-scooper-full",
    name: "COSCO CRICKET BAT SCOOPER-FULL",
    sku: "8901793180202",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 95,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-bat-striker-full",
    name: "COSCO CRICKET BAT STRIKER FULL",
    sku: "8901793180257",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 55,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-cricket-bat-striker-3",
    name: "COSCO CRICKET BAT STRIKER-3",
    sku: "8901793180189",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 40,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-bat-striker-4",
    name: "COSCO CRICKET BAT STRIKER-4",
    sku: "8901793180158",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 42,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-bat-striker-5",
    name: "COSCO CRICKET BAT STRIKER-5",
    sku: "8901793180165",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 44,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-bat-striker-6",
    name: "COSCO CRICKET BAT STRIKER-6",
    sku: "8901793180172",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 46,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-cricket-ball-club",
    name: "COSCO CRICKET BALL CLUB",
    sku: "8901793190249",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 28,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-ball-county",
    name: "COSCO CRICKET BALL COUNTY",
    sku: "8901793290237",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 35,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-set-t-20-full",
    name: "COSCO CRICKET SET T-20 FULL",
    sku: "8901793180387",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 400,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-cricket-set-t-20-4",
    name: "COSCO CRICKET SET T-20 -4",
    sku: "8901793180301",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 350,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-cricket-set-t-20-5",
    name: "COSCO CRICKET SET T-20 -5",
    sku: "8901793180295",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 360,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-cricket-set-t-20-6",
    name: "COSCO CRICKET SET T-20 -6",
    sku: "8901793180288",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 375,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-cricket-tennis-ball-heavy-weight",
    name: "COSCO CRICKET TENNIS BALL-HEAVY WEIGHT",
    sku: "8901793120024",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 8,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-cricket-tennis-ball-light-weight",
    name: "COSCO CRICKET TENNIS BALL-LIGHT WEIGHT",
    sku: "8901793120017",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 7,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-football-gloves-proector-m",
    name: "COSCO FOOTBALL GLOVES PROECTOR M",
    sku: "8901793390021",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 85,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-football-gloves-ultimax-m",
    name: "COSCO FOOTBALL GLOVES ULTIMAX M",
    sku: "8901793390038",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 115,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-football-net-nylon",
    name: "COSCO FOOTBALL NET NYLON",
    sku: "8901793350063",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Football",
    priceAed: 260,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-gloves-shield-assorted",
    name: "COSCO GLOVES SHIELD ASSORTED",
    sku: "8901793390014",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 47,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-gym-ball-55cm",
    name: "COSCO GYM BALL -55CM",
    sku: "8901793280247",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 52,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-gym-ball-75cm",
    name: "COSCO GYM BALL -75CM",
    sku: "8901793280056",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 69,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-hurdle-12",
    name: "COSCO HURDLE 12",
    sku: "8901793289318",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 14,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-hurdle-6",
    name: "COSCO HURDLE 6",
    sku: "8901793289295",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-jump-rope-hop",
    name: "COSCO JUMP ROPE HOP",
    sku: "8901793289288",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Training",
    priceAed: 12,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-medicine-ball-synery-1-kg",
    name: "COSCO MEDICINE BALL SYNERY 1 KG",
    sku: "8901793170111",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 48,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-medicine-ball-synery-3-kg",
    name: "COSCO MEDICINE BALL SYNERY 3 KG",
    sku: "8901793170135",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 72,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-medicine-ball-synery-2-kg",
    name: "COSCO MEDICINE BALL SYNERY 2 KG",
    sku: "8901793170128",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 60,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-medicine-ball-synery-4-kg",
    name: "COSCO MEDICINE BALL SYNERY 4 KG",
    sku: "8901793170142",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 85,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-medicine-ball-synery-5-kg",
    name: "COSCO MEDICINE BALL SYNERY 5 KG",
    sku: "8901793170159",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 95,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-netball-grip-5",
    name: "COSCO NETBALL GRIP-5",
    sku: "8901793170029",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Fitness",
    priceAed: 64,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-paddle-ballwool-tournament-yellow",
    name: "COSCO Paddle Ballwool Tournament-Yellow",
    sku: "8901793111008",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 28,
    unit: "Can",
    inStock: true,
  },
  {
    slug: "cosco-paddle-bat-attack-carbon-black",
    name: "COSCO Paddle Bat ATTACK Carbon Black",
    sku: "8901793111011",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 529,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-paddle-bat-battle-carbon-black",
    name: "COSCO Paddle Bat BATTLE Carbon Black",
    sku: "8901793111010",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 429,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-paddle-bat-bolt-carbon-black",
    name: "COSCO Paddle Bat BOLT Carbon Black",
    sku: "8901793111009",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 379,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-pickle-ball-indoor-26",
    name: "COSCO PICKLE BALL INDOOR 26",
    sku: "8901793410040",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 15,
    unit: "Pkt",
    inStock: true,
  },
  {
    slug: "cosco-pickle-ball-outdoor-40",
    name: "COSCO PICKLE BALL OUTDOOR 40",
    sku: "8901793410057",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 15,
    unit: "Pkt",
    inStock: true,
  },
  {
    slug: "cosco-pickle-bat-caron-arc",
    name: "COSCO PICKLE BAT CARON ARC",
    sku: "8901793410033",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 220,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-pickle-bat-punch",
    name: "COSCO PICKLE BAT PUNCH",
    sku: "8901793410026",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 140,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-pickle-bat-tango-blue",
    name: "COSCO PICKLE BAT TANGO BLUE",
    sku: "8901793410071",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 100,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "cosco-pickle-court-net-champion",
    name: "COSCO PICKLE COURT NET CHAMPION",
    sku: "8901793410449",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 4300,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-pickle-court-net-win",
    name: "COSCO PICKLE COURT NET WIN",
    sku: "8901793410064",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Pickleball",
    priceAed: 700,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-plastic-cricket-bat-size-3-sixxer",
    name: "COSCO PLASTIC CRICKET BAT SIZE-3 SIXXER",
    sku: "8901793180363",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 23,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-plastic-cricket-bat-size-4-sixxer",
    name: "COSCO PLASTIC CRICKET BAT SIZE-4 SIXXER",
    sku: "8901793180356",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 25,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-plastic-cricket-bat-size-6-sixxer",
    name: "COSCO PLASTIC CRICKET BAT SIZE-6 SIXXER",
    sku: "8901793180332",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 25,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-shin-guard-impact-assorted-senior",
    name: "COSCO SHIN GUARD IMPACT ASSORTED-SENIOR",
    sku: "8901793340033",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 17,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-shin-guard-shooter-assorted-senior",
    name: "COSCO SHIN GUARD SHOOTER ASSORTED-SENIOR",
    sku: "8901793340026",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 11,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-shinguard-kicker-senior",
    name: "COSCO SHINGUARD KICKER SENIOR",
    sku: "8901793340019",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 10,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-shinguard-rocky-senior",
    name: "COSCO SHINGUARD ROCKY SENIOR",
    sku: "8901793340071",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 12,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-shingurad-club-junor",
    name: "COSCO SHINGURAD CLUB JUNOR",
    sku: "8901793340064",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 10,
    unit: "Prs",
    inStock: true,
  },
  {
    slug: "cosco-swimmiung-cap-assorted",
    name: "COSCO SWIMMIUNG CAP ASSORTED",
    sku: "8901793250035",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Swimming",
    priceAed: 20,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-swimmiung-goggles-aqua-dash",
    name: "COSCO SWIMMIUNG GOGGLES AQUA DASH",
    sku: "8901793250066",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Swimming",
    priceAed: 42,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-swimmiung-goggles-aqua-jet",
    name: "COSCO SWIMMIUNG GOGGLES AQUA JET+",
    sku: "8901793250097",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Swimming",
    priceAed: 50,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-tennis-ball-all-court-1-3",
    name: "COSCO TENNIS BALL ALL COURT - 1*3",
    sku: "8901793110049",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Tennis",
    priceAed: 20,
    unit: "Can",
    inStock: true,
  },
  {
    slug: "cosco-tennis-ball-championship",
    name: "COSCO TENNIS BALL CHAMPIONSHIP",
    sku: "8901793110018",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Tennis",
    priceAed: 24,
    unit: "Can",
    inStock: true,
  },
  {
    slug: "cosco-tennis-ball-fun-time-1-3",
    name: "COSCO TENNIS BALL FUN TIME- 1*3",
    sku: "8901793110056",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Tennis",
    priceAed: 15,
    unit: "Can",
    inStock: true,
  },
  {
    slug: "cosco-tennis-net-nylon",
    name: "COSCO TENNIS NET NYLON",
    sku: "8901793350070",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Tennis",
    priceAed: 400,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-training-set-max",
    name: "COSCO TRAINING SET MAX",
    sku: "8901793280841",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 70,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-acclaim-4",
    name: "COSCO VOLLEYBALL ACCLAIM -4",
    sku: "8901793150076",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 68,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-all-star-4",
    name: "COSCO VOLLEYBALL ALL STAR -4",
    sku: "8901793150328",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 37,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-aspire",
    name: "COSCO VOLLEYBALL ASPIRE",
    sku: "8901793150281",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 58,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-astra",
    name: "COSCO VOLLEYBALL ASTRA",
    sku: "8901793150342",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 43,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-beach-volley",
    name: "COSCO VOLLEYBALL BEACH VOLLEY",
    sku: "8901793150175",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 60,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-cvb-500",
    name: "COSCO VOLLEYBALL CVB 500",
    sku: "8901793150373",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 100,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-cvb-700",
    name: "COSCO VOLLEYBALL CVB 700",
    sku: "8901793150380",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 105,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-gold-star",
    name: "COSCO VOLLEYBALL GOLD STAR",
    sku: "8901793150052",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 56,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-net-nylon",
    name: "COSCO VOLLEYBALL NET NYLON",
    sku: "8901793350056",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 97,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-net-tournament",
    name: "COSCO VOLLEYBALL NET TOURNAMENT",
    sku: "8901793350094",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 300,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-smash-volley",
    name: "COSCO VOLLEYBALL SMASH VOLLEY",
    sku: "8901793150045",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 77,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-striker",
    name: "COSCO VOLLEYBALL STRIKER",
    sku: "8901793150182",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 52,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-super-volley",
    name: "COSCO VOLLEYBALL SUPER VOLLEY",
    sku: "8901793150021",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 100,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-volleyball-attacker",
    name: "COSCO VOLLEYBALL ATTACKER",
    sku: "8901793150250",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Volleyball",
    priceAed: 62,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-waterpolo-ball-international-5",
    name: "COSCO WATERPOLO BALL INTERNATIONAL-5",
    sku: "8901793170012",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 54,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-rugby-ball-sportco",
    name: "COSCO RUGBY BALL SPORTCO",
    sku: "8901793170067",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 55,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "cosco-wicket-keeping-gloves-test",
    name: "COSCO WICKET KEEPING GLOVES TEST",
    sku: "8901793190119",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 125,
    unit: "Set",
    inStock: false,
  },
  {
    slug: "cosco-wicket-keeping-leegguard-test",
    name: "COSCO WICKET KEEPING LEEGGUARD TEST",
    sku: "8901793190096",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 115,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "cosco-wind-ball-bouncer",
    name: "COSCO WIND BALL BOUNCER",
    sku: "8901793120093",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 20,
    unit: "Can",
    inStock: false,
  },
  {
    slug: "cosco-yoga-mat-fit",
    name: "COSCO YOGA MAT FIT",
    sku: "8901793289202",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Fitness",
    priceAed: 45,
    unit: "pc",
    inStock: true,
  },
  {
    slug: "cricket-stump-set-out",
    name: "CRICKET STUMP SET OUT",
    sku: "8901793180370",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Cricket",
    priceAed: 45,
    unit: "Set",
    inStock: false,
  },
  {
    slug: "cosco-ball-bag-voctory",
    name: "COSCO BALL BAG VOCTORY",
    sku: "8901793289196",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Sports Equipment",
    priceAed: 35,
    unit: "PC",
    inStock: true,
  },
  {
    slug: "cosco-carrom-board-emerald",
    name: "COSCO CARROM BOARD EMERALD",
    sku: "8901793260027",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Indoor Games",
    priceAed: 330,
    unit: "PC",
    inStock: false,
  },
  {
    slug: "cosco-carrom-board-sapphire",
    name: "COSCO CARROM BOARD SAPPHIRE",
    sku: "8901793260034",
    brandSlug: "cosco",
    brandName: "Cosco",
    category: "Indoor Games",
    priceAed: 230,
    unit: "PC",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-3-star-future",
    name: "STIGA TT BAT 3 STAR FUTURE",
    sku: "7318688027640",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 200,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-hobby-haze-concave",
    name: "STIGA TT BAT HOBBY HAZE CONCAVE",
    sku: "7318688015999",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 48,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-hobby-hearty",
    name: "STIGA TT BAT HOBBY HEARTY",
    sku: "7318688020504",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 52,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-hobby-hefty",
    name: "STIGA TT BAT- HOBBY HEFTY",
    sku: "7318688020511",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 50,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-hobby-hype",
    name: "STIGA TT BAT HOBBY HYPE",
    sku: "7318688013032",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 45,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-bat-oracle",
    name: "STIGA TT BAT ORACLE",
    sku: "7318688013056",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 59,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-bat-rough",
    name: "STIGA TT BAT ROUGH",
    sku: "7318688020528",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 48,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-set-sable",
    name: "STIGA TT SET- SABLE",
    sku: "7318688020474",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 87,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-set-activity",
    name: "STIGA TT SET- ACTIVITY",
    sku: "7318688028012",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 200,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-1-star-blaze",
    name: "STIGA TT BAT 1 STAR BLAZE",
    sku: "7318688028128",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 40,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-check-hobby",
    name: "STIGA TT BAT CHECK HOBBY",
    sku: "73218688028104",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 25,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-set-technique",
    name: "STIGA TT SET- TECHNIQUE",
    sku: "7318688012943",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 80,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-2-star-react",
    name: "STIGA TT BAT 2 STAR REACT",
    sku: "7318688027770",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 100,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-4-star-vision",
    name: "STIGA TT BAT 4 STAR VISION",
    sku: "7318688027664",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 370,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-5-star-prestige",
    name: "STIGA TT BAT 5 STAR PRESTIGE",
    sku: "7318688027688",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 485,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-2-star-artist",
    name: "STIGA TT BAT 2 STAR ARTIST",
    sku: "7318688028142",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 55,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-bat-5-star-flexure",
    name: "STIGA TT BAT 5 STAR- FLEXURE",
    sku: "7318688016095",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 400,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-bat-3-star-cybershape-future",
    name: "STIGA TT BAT 3 STAR - CYBERSHAPE FUTURE",
    sku: "7318688036925",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 300,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-bat-3-star-pro-wrb-blue-edition",
    name: "STIGA TT BAT 3 STAR PRO WRB BLUE EDITION",
    sku: "7318688035232",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 275,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-instinct-hobby",
    name: "STIGA TT BAT INSTINCT HOBBY",
    sku: "7318688027749",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 60,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-set-sway-hobby",
    name: "STIGA TT BAT SET SWAY HOBBY",
    sku: "7318688028074",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 85,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-1-star-evolve",
    name: "STIGA TT BAT 1 STAR EVOLVE",
    sku: "7318688027756",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 100,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-5-star-pro-carbon-plus-cybershape",
    name: "STIGA TT BAT 5 STAR PRO CARBON PLUS CYBERSHAPE",
    sku: "7318688036932",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 670,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-cybershape-hobby",
    name: "STIGA TT BAT CYBERSHAPE HOBBY",
    sku: "7318688038011",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 55,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-3-star-wrb-royal",
    name: "STIGA TT BAT 3 STAR WRB ROYAL",
    sku: "7318688025356",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 280,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-1-star-cybershape",
    name: "STIGA TT BAT 1 STAR CYBERSHAPE",
    sku: "7318688038714",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 80,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-5-star-pro-carbon-plus",
    name: "STIGA TT BAT 5 STAR PRO CARBON PLUS",
    sku: "7318688032453",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 670,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-seasons-anywhere-black",
    name: "STIGA TT BAT SEASONS ANYWHERE BLACK",
    sku: "7318688035508",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 95,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-3-star-trinity-v2",
    name: "STIGA TT BAT 3 STAR- TRINITY V2",
    sku: "7318688041875",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 150,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-4-star-royal-crystal",
    name: "STIGA TT BAT 4 STAR ROYAL CRYSTAL",
    sku: "7318688025363",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 400,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-5-star-royal-carbon",
    name: "STIGA TT BAT 5 STAR ROYAL CARBON",
    sku: "7318688025370",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 650,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-5-star-flexure-v2",
    name: "STIGA TT BAT 5 STAR- FLEXURE V2",
    sku: "7318688041882",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 350,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-clash-hobby",
    name: "STIGA TT BAT CLASH HOBBY",
    sku: "7318688028098",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 25,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-set-sonic",
    name: "STIGA TT SET- SONIC",
    sku: "7318688015975",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 90,
    unit: "Set",
    inStock: true,
  },
  {
    slug: "stiga-tt-bat-roast",
    name: "STIGA TT- BAT ROAST",
    sku: "7318688020535",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 59,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-set-sonic-v2",
    name: "STIGA TT SET- SONIC V2",
    sku: "7318688041868",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Bats",
    priceAed: 90,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-balls-3-star-perform-white-1-6",
    name: "STIGA TT BALLS 3 STAR PERFORM WHITE (1*6)",
    sku: "7318688038448",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Balls",
    priceAed: 45,
    unit: "Pkt",
    inStock: true,
  },
  {
    slug: "stiga-tt-balls-cup-white-1-12",
    name: "STIGA TT BALLS CUP WHITE (1*12)",
    sku: "7318688038424",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Balls",
    priceAed: 35,
    unit: "Pkt",
    inStock: false,
  },
  {
    slug: "stiga-tt-balls-winner-white-1-6",
    name: "STIGA TT BALLS WINNER WHITE (1*6)",
    sku: "7318688020337",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Balls",
    priceAed: 30,
    unit: "Pkt",
    inStock: false,
  },
  {
    slug: "stiga-tt-balls-cup-1-6-orange",
    name: "STIGA TT BALLS CUP(1*6)- ORANGE",
    sku: "7318688020368",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Balls",
    priceAed: 20,
    unit: "5",
    inStock: false,
  },
  {
    slug: "stiga-table-winner-indoor",
    name: "STIGA TABLE WINNER INDOOR",
    sku: "4013771220825",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 3000,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-table-winner-outdoor",
    name: "STIGA TABLE WINNER OUTDOOR",
    sku: "4013771220856",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 4000,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-table-club-roller-15mm",
    name: "STIGA TABLE CLUB ROLLER 15MM",
    sku: "7318688012707",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 2200,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-table-action-roller",
    name: "STIGA TABLE ACTION ROLLER",
    sku: "4013771221679",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 3100,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-table-athlete-roller-18mm",
    name: "STIGA TABLE ATHLETE ROLLER 18mm",
    sku: "7318688014497",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 2600,
    unit: "Pc",
    inStock: false,
  },
  {
    slug: "stiga-tt-net-seasons-anywhere",
    name: "STIGA TT NET SEASONS ANYWHERE",
    sku: "7318688041851",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 75,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-net-post-clip-on",
    name: "STIGA TT NET & POST- CLIP ON",
    sku: "7318686134005",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 80,
    unit: "Pc",
    inStock: true,
  },
  {
    slug: "stiga-tt-net-post-champ",
    name: "STIGA TT NET & POST- CHAMP",
    sku: "7318686360008",
    brandSlug: "stiga",
    brandName: "STIGA",
    category: "Tables & Nets",
    priceAed: 90,
    unit: "Pc",
    inStock: true,
  },
];
