import { site } from "./site";
import type { Location } from "./types";

export const locations: Location[] = [
  {
    id: "dubai-flagship",
    name: "ARP Flagship Store - Dubai",
    storeType: "Official Branch",
    emirate: "Dubai",
    city: "Dubai",
    address: "Client-supplied Dubai address, UAE",
    phone: "+971 4 123 4567",
    hours: "Sun - Sat: client-supplied hours",
    brands: ["Yonex", "STIGA", "Cosco", "LP Support"],
    directionsUrl: "https://maps.google.com/?q=Dubai",
    image: site.assets.store,
    distance: "2.4 km",
  },
  {
    id: "abu-dhabi-branch",
    name: "ARP Abu Dhabi Branch",
    storeType: "Official Branch",
    emirate: "Abu Dhabi",
    city: "Abu Dhabi",
    address: "Client-supplied Abu Dhabi address, UAE",
    phone: "+971 2 654 3210",
    hours: "Sun - Sat: client-supplied hours",
    brands: ["Yonex", "Cosco", "SS Cricket"],
    directionsUrl: "https://maps.google.com/?q=Abu+Dhabi",
    image: site.assets.store,
    distance: "12.0 km",
  },
  {
    id: "sharjah-branch",
    name: "ARP Sharjah Branch",
    storeType: "Official Branch",
    emirate: "Sharjah",
    city: "Sharjah",
    address: "Client-supplied Sharjah address, UAE",
    phone: "+971 6 543 2109",
    hours: "Sun - Sat: client-supplied hours",
    brands: ["STIGA", "Cosco", "Surco"],
    directionsUrl: "https://maps.google.com/?q=Sharjah",
    image: site.assets.store,
    distance: "25 km",
  },
  {
    id: "champion-sports",
    name: "Champion Sports LLC",
    storeType: "Authorized Reseller",
    emirate: "Dubai",
    city: "Dubai",
    address: "Client-supplied reseller address, UAE",
    phone: "+971 4 000 0000",
    hours: "Client-supplied hours",
    brands: ["Yonex", "LP Support"],
    directionsUrl: "https://maps.google.com/?q=Dubai+Sports+Store",
  },
  {
    id: "active-play",
    name: "Active Play Store",
    storeType: "Authorized Reseller",
    emirate: "Abu Dhabi",
    city: "Abu Dhabi",
    address: "Client-supplied reseller address, UAE",
    phone: "+971 2 000 0000",
    hours: "Client-supplied hours",
    brands: ["Cosco", "SS Cricket"],
    directionsUrl: "https://maps.google.com/?q=Abu+Dhabi+Sports+Store",
  },
  {
    id: "game-on-sports",
    name: "Game On Sports",
    storeType: "Authorized Reseller",
    emirate: "Sharjah",
    city: "Sharjah",
    address: "Client-supplied reseller address, UAE",
    phone: "+971 6 000 0000",
    hours: "Client-supplied hours",
    brands: ["STIGA", "Surco"],
    directionsUrl: "https://maps.google.com/?q=Sharjah+Sports+Store",
  },
];
