export const sportsContent = {
  hero: {
    eyebrow: "Sports Categories",
    title: "Performance Across Every Discipline",
    body: "Explore the sports ARP supports through official brand distribution, wholesale supply and local retail access across the UAE.",
  },
  categories: [
    {
      slug: "racquet-sports",
      title: "Racquet Sports",
      description: "Badminton, tennis and performance racquet equipment from official partners.",
      brandSlugs: ["yonex"],
      filter: "Racquet Sports",
      /** Shop categories that make up this discipline — drives live product counts. */
      shopCategories: ["Badminton", "Tennis", "Racquets", "Shoes", "Apparel", "Shuttlecocks"],
      highlights: ["Tournament racquets", "Court shoes", "Shuttlecocks"],
    },
    {
      slug: "table-tennis",
      title: "Table Tennis",
      description: "Tables, blades, rubbers and accessories for clubs, schools and players.",
      brandSlugs: ["stiga"],
      filter: "Table Tennis",
      shopCategories: ["Bats", "Balls", "Tables & Nets"],
      highlights: ["Competition tables", "3-star balls", "Club bats"],
    },
    {
      slug: "cricket",
      title: "Cricket",
      description: "Bats, protection and training gear for academies, teams and retailers.",
      brandSlugs: ["ss-cricket"],
      filter: "Cricket",
      shopCategories: ["Cricket"],
      highlights: ["Bats", "Protection", "Team kit"],
    },
    {
      slug: "team-sports",
      title: "Team Sports",
      description: "Multi-sport goods for schools, clubs and institutional programmes.",
      brandSlugs: ["cosco", "surco"],
      filter: "Sports Goods",
      shopCategories: [
        "Football",
        "Basketball",
        "Volleyball",
        "Sports Equipment",
        "Training",
        "Pickleball",
        "Swimming",
        "Indoor Games",
      ],
      highlights: ["Match balls", "Training aids", "Court equipment"],
    },
    {
      slug: "fitness-support",
      title: "Fitness & Support",
      description: "Supports, recovery and protection products for training and everyday use.",
      brandSlugs: ["lp-support"],
      filter: "Supports & Recovery",
      shopCategories: ["Fitness"],
      highlights: ["Braces & supports", "Weights", "Recovery"],
    },
  ],
};
