import { site } from "./site";
import type {
  AuthorizedReseller,
  StoreAmenity,
  StoreBranch,
  StoreCity,
  MapPoint,
} from "./types";

/**
 * Store network used by /locations and /authorized-resellers.
 *
 * Kept separate from `content/locations.ts` so the richer fields these two pages
 * need (opening-hours breakdown, amenities, map coordinates, reseller logos) do
 * not disturb the simpler dataset the older LocationFinder reads.
 */

/** Anchor points for the schematic UAE map, as percentages of the map box. */
export const cityPoints: Record<StoreCity, MapPoint> = {
  Dubai: { x: 48, y: 40 },
  Sharjah: { x: 60, y: 32 },
  Ajman: { x: 65, y: 25 },
  "Abu Dhabi": { x: 18, y: 70 },
  "Al Ain": { x: 72, y: 64 },
};

/** Cities offered as primary filter chips; the rest sit behind the "More" toggle. */
export const primaryCities: StoreCity[] = ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain"];
export const secondaryCities: StoreCity[] = ["Ajman"];

export const storeCategories = [
  "Sports Equipment",
  "Fitness & Accessories",
  "Team Sports",
  "Racquet Sports",
  "Table Tennis",
];

export const storeSports = [
  "Badminton",
  "Table Tennis",
  "Cricket",
  "Tennis",
  "Football",
  "Fitness",
];

/**
 * Ordered for display — grouped by city rather than sorted by distance, so the
 * first page of results reads Dubai, Dubai, Abu Dhabi, Sharjah.
 */
export const storeBranches: StoreBranch[] = [
  // Real branch details from the ARP business card (25 July 2026).
  {
    id: "dubai-flagship",
    name: "Branch 01 - Bur Dubai",
    kind: "Main Showroom",
    officialBranch: true,
    city: "Dubai",
    area: "Bur Dubai",
    address: "Shop No 1, Al Gassimi Bldg No 2, Souq Al Khabeer, Bur Dubai, Dubai, UAE",
    distance: "2.4 km",
    phone: "+971 4 222 3928",
    whatsapp: "+971 58 604 5409",
    hoursSummary: "Sun – Sat: 9:00 AM – 9:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "9:00 AM – 9:00 PM" },
      { days: "Friday", time: "2:00 PM – 9:00 PM" },
      { days: "Saturday", time: "9:00 AM – 9:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts", "Easy Returns", "Secure Payments"],
    brands: ["Yonex", "STIGA", "Cosco", "LP Support"],
    categories: ["Sports Equipment", "Racquet Sports", "Fitness & Accessories"],
    sports: ["Badminton", "Table Tennis", "Tennis", "Fitness"],
    image: site.assets.store,
    directionsUrl: "https://maps.app.goo.gl/hTjeTCEmSovvHmXA7",
    map: { x: 48, y: 40 },
  },
  {
    id: "dubai-hills",
    name: "ARP Sports Hub – Dubai Hills",
    kind: "Pro Shop",
    officialBranch: false,
    city: "Dubai",
    area: "Dubai Hills",
    address: "Dubai Hills Mall, Dubai, UAE",
    distance: "8.7 km",
    phone: "+971 4 567 8901",
    whatsapp: "+971 50 567 8901",
    hoursSummary: "Sun – Sat: 10:00 AM – 10:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "10:00 AM – 10:00 PM" },
      { days: "Friday", time: "2:00 PM – 11:00 PM" },
      { days: "Saturday", time: "10:00 AM – 11:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts", "Secure Payments"],
    brands: ["Yonex", "LP Support"],
    categories: ["Racquet Sports", "Fitness & Accessories"],
    sports: ["Badminton", "Tennis", "Fitness"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Dubai+Hills+Mall+Dubai",
    map: { x: 44, y: 44 },
  },
  {
    id: "abu-dhabi-showroom",
    name: "ARP Abu Dhabi Showroom",
    kind: "Showroom",
    officialBranch: false,
    city: "Abu Dhabi",
    area: "Al Zahiyah",
    address: "Najda Street, Al Zahiyah, Abu Dhabi, UAE",
    distance: "120 km",
    phone: "+971 2 654 3210",
    whatsapp: "+971 50 654 3210",
    hoursSummary: "Sun – Sat: 9:00 AM – 8:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "9:00 AM – 8:00 PM" },
      { days: "Friday", time: "2:00 PM – 8:00 PM" },
      { days: "Saturday", time: "9:00 AM – 8:00 PM" },
    ],
    amenities: ["Product Experts", "Easy Returns", "Secure Payments"],
    brands: ["Yonex", "Cosco"],
    categories: ["Sports Equipment", "Team Sports"],
    sports: ["Cricket", "Football", "Badminton"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Najda+Street+Al+Zahiyah+Abu+Dhabi",
    map: { x: 18, y: 70 },
  },
  {
    id: "sharjah-sports-store",
    name: "ARP Sharjah Sports Store",
    kind: "Showroom",
    officialBranch: false,
    city: "Sharjah",
    area: "Al Taawun",
    address: "Mega Mall, Al Taawun, Sharjah, UAE",
    distance: "25 km",
    phone: "+971 6 543 2109",
    whatsapp: "+971 50 543 2109",
    hoursSummary: "Sun – Sat: 10:00 AM – 10:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "10:00 AM – 10:00 PM" },
      { days: "Friday", time: "2:00 PM – 10:00 PM" },
      { days: "Saturday", time: "10:00 AM – 10:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts", "Secure Payments"],
    brands: ["STIGA", "Cosco"],
    categories: ["Table Tennis", "Sports Equipment"],
    sports: ["Table Tennis", "Football"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Mega+Mall+Al+Taawun+Sharjah",
    map: { x: 60, y: 32 },
  },
  {
    id: "dubai-deira",
    name: "ARP Deira Sports Centre",
    kind: "Showroom",
    officialBranch: false,
    city: "Dubai",
    area: "Al Rigga",
    address: "Al Rigga Road, Deira, Dubai, UAE",
    distance: "12.6 km",
    phone: "+971 4 223 4488",
    whatsapp: "+971 50 223 4488",
    hoursSummary: "Sun – Sat: 9:00 AM – 9:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "9:00 AM – 9:00 PM" },
      { days: "Friday", time: "2:00 PM – 9:00 PM" },
      { days: "Saturday", time: "9:00 AM – 9:00 PM" },
    ],
    amenities: ["Product Experts", "Easy Returns", "Secure Payments"],
    brands: ["Cosco", "SS Cricket", "Surco"],
    categories: ["Team Sports", "Sports Equipment"],
    sports: ["Cricket", "Football"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Al+Rigga+Road+Deira+Dubai",
    map: { x: 52, y: 37 },
  },
  {
    id: "dubai-marina",
    name: "ARP Marina Outlet",
    kind: "Showroom",
    officialBranch: false,
    city: "Dubai",
    area: "Dubai Marina",
    address: "Marina Walk, Dubai Marina, Dubai, UAE",
    distance: "16.2 km",
    phone: "+971 4 399 7712",
    whatsapp: "+971 50 399 7712",
    hoursSummary: "Sun – Sat: 10:00 AM – 10:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "10:00 AM – 10:00 PM" },
      { days: "Friday", time: "2:00 PM – 10:00 PM" },
      { days: "Saturday", time: "10:00 AM – 10:00 PM" },
    ],
    amenities: ["Product Experts", "Secure Payments"],
    brands: ["Yonex", "LP Support"],
    categories: ["Fitness & Accessories", "Racquet Sports"],
    sports: ["Fitness", "Tennis"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Marina+Walk+Dubai+Marina",
    map: { x: 43, y: 37 },
  },
  {
    id: "dubai-barsha",
    name: "ARP Al Barsha Partner Store",
    kind: "Partner Store",
    officialBranch: false,
    city: "Dubai",
    area: "Al Barsha 1",
    address: "Al Barsha 1, Dubai, UAE",
    distance: "10.4 km",
    phone: "+971 4 388 2050",
    whatsapp: "+971 50 388 2050",
    hoursSummary: "Sun – Sat: 10:00 AM – 9:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "10:00 AM – 9:00 PM" },
      { days: "Friday", time: "2:00 PM – 9:00 PM" },
      { days: "Saturday", time: "10:00 AM – 9:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts"],
    brands: ["Yonex", "STIGA"],
    categories: ["Racquet Sports", "Table Tennis"],
    sports: ["Badminton", "Table Tennis"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Al+Barsha+1+Dubai",
    map: { x: 46, y: 45 },
  },
  {
    id: "dubai-jumeirah",
    name: "ARP Jumeirah Service Point",
    kind: "Service Point",
    officialBranch: false,
    city: "Dubai",
    area: "Umm Suqeim 2",
    address: "Jumeirah Beach Road, Umm Suqeim 2, Dubai, UAE",
    distance: "9.1 km",
    phone: "+971 4 344 6620",
    whatsapp: "+971 50 344 6620",
    hoursSummary: "Sun – Sat: 9:00 AM – 7:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "9:00 AM – 7:00 PM" },
      { days: "Friday", time: "Closed" },
      { days: "Saturday", time: "9:00 AM – 5:00 PM" },
    ],
    amenities: ["Free Parking", "Easy Returns"],
    brands: ["Yonex", "LP Support"],
    categories: ["Racquet Sports", "Fitness & Accessories"],
    sports: ["Badminton", "Tennis"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Umm+Suqeim+2+Jumeirah+Dubai",
    map: { x: 50, y: 44 },
  },
  {
    id: "abu-dhabi-branch",
    name: "Branch 02 - Al Karama",
    kind: "Showroom",
    officialBranch: true,
    city: "Dubai",
    area: "Al Karama",
    address: "Saeed Menanah Bldg A-5, Shop No 2, 318/12 Street, Al Karama, Dubai, UAE",
    distance: "4.1 km",
    phone: "+971 4 337 3315",
    whatsapp: "+971 58 604 5408",
    hoursSummary: "Sun – Sat: 9:00 AM – 9:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "9:00 AM – 9:00 PM" },
      { days: "Friday", time: "2:00 PM – 9:00 PM" },
      { days: "Saturday", time: "9:00 AM – 9:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts", "Easy Returns", "Secure Payments"],
    brands: ["Yonex", "Cosco"],
    categories: ["Sports Equipment", "Team Sports", "Racquet Sports"],
    sports: ["Cricket", "Badminton", "Football"],
    image: site.assets.store,
    directionsUrl: "https://maps.app.goo.gl/VnQQT4i6WrYVctfL7",
    map: { x: 51, y: 37 },
  },
  {
    id: "sharjah-branch",
    name: "Branch 03 - Al Quoz",
    kind: "Pro Shop",
    officialBranch: true,
    city: "Dubai",
    area: "Al Quoz Industrial Area 3",
    address: "Opposite Al Quoz Mall, Al Quoz Industrial Area 3, Dubai, UAE",
    distance: "8.9 km",
    phone: "+971 55 287 1234",
    whatsapp: "+971 55 287 1234",
    hoursSummary: "Sun – Sat: 9:00 AM – 9:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "9:00 AM – 9:00 PM" },
      { days: "Friday", time: "2:00 PM – 9:00 PM" },
      { days: "Saturday", time: "9:00 AM – 9:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts", "Easy Returns", "Secure Payments"],
    brands: ["STIGA", "Cosco"],
    categories: ["Table Tennis", "Sports Equipment", "Team Sports"],
    sports: ["Table Tennis", "Football", "Cricket"],
    image: site.assets.store,
    directionsUrl: "https://www.google.com/maps/place/Pioneers+Badminton+Hub/@25.1235867,55.2186242,1080m/data=!3m1!1e3!4m15!1m8!3m7!1s0x3e5f6b6944663df1:0xd5834a4b45ebd61d!2sPioneers+Badminton+Hub!8m2!3d25.1235018!4d55.2212178!10e1!16s%2Fg%2F11khtk8hgz!3m5!1s0x3e5f6b6944663df1:0xd5834a4b45ebd61d!8m2!3d25.1235018!4d55.2212178!16s%2Fg%2F11khtk8hgz!5m1!1e1?entry=ttu&g_ep=EgoyMDI2MDgwNS4xIKXMDSoASAFQAw%3D%3D",
    map: { x: 47, y: 43 },
  },
  {
    id: "sharjah-depot",
    name: "ARP Sharjah Depot",
    kind: "Service Point",
    officialBranch: false,
    city: "Sharjah",
    area: "Industrial Area 5",
    address: "Industrial Area 5, Sharjah, UAE",
    distance: "28 km",
    phone: "+971 6 534 9900",
    whatsapp: "+971 50 534 9900",
    hoursSummary: "Sun – Thu: 8:00 AM – 6:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "8:00 AM – 6:00 PM" },
      { days: "Friday", time: "Closed" },
      { days: "Saturday", time: "8:00 AM – 1:00 PM" },
    ],
    amenities: ["Free Parking", "Easy Returns"],
    brands: ["Cosco", "Surco", "SS Cricket"],
    categories: ["Sports Equipment", "Team Sports"],
    sports: ["Football", "Cricket"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Industrial+Area+5+Sharjah",
    map: { x: 58, y: 35 },
  },
  {
    id: "al-ain-corner",
    name: "ARP Al Ain Sports Corner",
    kind: "Showroom",
    officialBranch: false,
    city: "Al Ain",
    area: "Al Jimi",
    address: "Al Jimi Mall, Al Ain, UAE",
    distance: "145 km",
    phone: "+971 3 762 5510",
    whatsapp: "+971 50 762 5510",
    hoursSummary: "Sun – Sat: 10:00 AM – 10:00 PM",
    openingHours: [
      { days: "Sunday – Thursday", time: "10:00 AM – 10:00 PM" },
      { days: "Friday", time: "2:00 PM – 10:00 PM" },
      { days: "Saturday", time: "10:00 AM – 10:00 PM" },
    ],
    amenities: ["Free Parking", "Product Experts", "Secure Payments"],
    brands: ["Cosco", "SS Cricket", "Surco"],
    categories: ["Sports Equipment", "Team Sports"],
    sports: ["Cricket", "Football"],
    image: site.assets.store,
    directionsUrl: "https://maps.google.com/?q=Al+Jimi+Mall+Al+Ain",
    map: { x: 72, y: 64 },
  },
];

export const authorizedResellers: AuthorizedReseller[] = [
  {
    id: "champion-sports",
    name: "Champion Sports LLC",
    category: "Sports Equipment",
    city: "Dubai",
    area: "Al Barsha",
    address: "Al Barsha 2, Dubai, UAE",
    phone: "+971 4 399 1180",
    logoText: "Champion Sports",
    logoClass: "reseller-mark-champion",
    brands: ["Yonex", "LP Support"],
    sports: ["Badminton", "Fitness"],
    directionsUrl: "https://maps.google.com/?q=Al+Barsha+2+Dubai+sports+store",
    map: { x: 45, y: 43 },
  },
  {
    id: "active-play",
    name: "Active Play Store",
    category: "Fitness & Accessories",
    city: "Abu Dhabi",
    area: "Khalidiya",
    address: "Zayed the First Street, Al Khalidiya, Abu Dhabi, UAE",
    phone: "+971 2 665 4020",
    logoText: "Active Play",
    logoClass: "reseller-mark-active",
    brands: ["Cosco", "SS Cricket"],
    sports: ["Fitness", "Cricket"],
    directionsUrl: "https://maps.google.com/?q=Al+Khalidiya+Abu+Dhabi+sports+store",
    map: { x: 16, y: 73 },
  },
  {
    id: "game-on-sports",
    name: "Game On Sports",
    category: "Team Sports",
    city: "Sharjah",
    area: "Al Majaz",
    address: "Al Majaz 3, Sharjah, UAE",
    phone: "+971 6 556 3390",
    logoText: "Game On",
    logoClass: "reseller-mark-gameon",
    brands: ["STIGA", "Surco"],
    sports: ["Football", "Table Tennis"],
    directionsUrl: "https://maps.google.com/?q=Al+Majaz+3+Sharjah+sports+store",
    map: { x: 62, y: 34 },
  },
  {
    id: "profit-trading",
    name: "ProFit Trading LLC",
    category: "Fitness & Accessories",
    city: "Ajman",
    area: "Al Nuaimiya",
    address: "Al Nuaimiya 2, Ajman, UAE",
    phone: "+971 6 742 8815",
    logoText: "ProFit",
    logoClass: "reseller-mark-profit",
    brands: ["LP Support", "Cosco"],
    sports: ["Fitness", "Football"],
    directionsUrl: "https://maps.google.com/?q=Al+Nuaimiya+Ajman+sports+store",
    map: { x: 66, y: 25 },
  },
  {
    id: "elite-racquet",
    name: "Elite Racquet House",
    category: "Racquet Sports",
    city: "Dubai",
    area: "Al Quoz",
    address: "Al Quoz 3, Dubai, UAE",
    phone: "+971 4 340 7725",
    logoText: "Elite Racquet",
    logoClass: "reseller-mark-elite",
    brands: ["Yonex", "STIGA"],
    sports: ["Badminton", "Tennis", "Table Tennis"],
    directionsUrl: "https://maps.google.com/?q=Al+Quoz+3+Dubai+racquet+store",
    map: { x: 50, y: 42 },
  },
  {
    id: "al-ain-depot",
    name: "Al Ain Sports Depot",
    category: "Sports Equipment",
    city: "Al Ain",
    area: "Al Jimi",
    address: "Al Jimi, Al Ain, UAE",
    phone: "+971 3 764 1190",
    logoText: "Al Ain Depot",
    logoClass: "reseller-mark-alain",
    brands: ["Cosco", "SS Cricket", "Surco"],
    sports: ["Cricket", "Football"],
    directionsUrl: "https://maps.google.com/?q=Al+Jimi+Al+Ain+sports+store",
    map: { x: 74, y: 62 },
  },
];

export const officialBranches = storeBranches.filter((branch) => branch.officialBranch);

/** Support details shown in the "Need Help?" panel on /locations. */
export const storeSupport = {
  blurb: "Our team is here to help you find the right gear.",
  phone: "800 ARP 277",
  phoneHref: "tel:800277277",
  email: "info@arpgroup.ae",
};

export const amenityOrder: StoreAmenity[] = [
  "Free Parking",
  "Product Experts",
  "Easy Returns",
  "Secure Payments",
];

/** Reasons to buy through the verified network, shown on /authorized-resellers. */
export const verifiedSourceProof = [
  { value: "100%", label: "Genuine Products" },
  { value: "Authorized", label: "Partners Only" },
  { value: "Expert", label: "Product Knowledge" },
  { value: "Trusted", label: "After-Sales Support" },
];

export function countByCity(cities: StoreCity[] = [...primaryCities, ...secondaryCities]) {
  return cities
    .map((city) => ({
      city,
      count: storeBranches.filter((branch) => branch.city === city).length,
      point: cityPoints[city],
    }))
    .filter((entry) => entry.count > 0);
}
